services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # image: golang:1.22.3-alpine
    # command: ['cd /go/src/h24s_19', 'go mod download', 'go run main.go']
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/h24s_19
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
