services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    # image: golang:1.22.3-alpine
    # command: ['cd /go/src/h24s_19', 'go mod download', 'go run main.go']
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      TZ: "Asia/Tokyo"
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/h24s_19
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql --user=user --password=password --execute "SHOW DATABASES;"
      interval: 1s
      timeout: 10s
      retries: 30
